Repository 250421/CineMatch-P2-Frontend, pull requests merged in 2025-05, with the labels that each got.

#7 Create post
  package-lock.json
  package.json
  src/components/shared/navbar.tsx
  src/components/ui/autosize-textarea.tsx
  src/components/ui/select.tsx
  src/features/posts/components/post-card.tsx
  src/features/posts/hooks/use-create-post.ts
  src/features/posts/models/post.tsx
  src/features/posts/schemas/create-post-schema.ts
  src/routeTree.gen.ts
  src/routes/(auth)/_auth.message-board.$boardId.tsx
  src/routes/(auth)/_auth.new-post.tsx
Labels: enhancement

#8 Delete posts
  src/components/shared/delete-prompt-dialog.tsx
  src/features/auth/model/creator.ts
  src/features/boards/components/message-board.tsx
  src/features/posts/components/post-card.tsx
  src/features/posts/hooks/use-delete-post.ts
  src/features/posts/models/post.tsx
Labels: enhancement

#9 Jest test
  .gitignore
  babel.config.json
  jest.config.ts
  jest.setup.ts
  package-lock.json
  package.json
  src/__tests__/message-board.spec.tsx
  src/__tests__/register.spec.tsx
  src/components/shared/no-post-found.tsx
  src/components/shared/requirement.tsx
  src/features/boards/components/message-board.tsx
  src/lib/axios-config.ts
  src/lib/utils.ts
  src/routes/(auth)/_auth.message-board.$boardId.tsx
  src/routes/(public)/_public.login.tsx
  src/routes/(public)/_public.register.tsx
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: enhancement

#12 Ratings
  src/features/boards/components/message-board.tsx
  src/features/posts/components/interaction-button.tsx
  src/features/posts/components/post-card.tsx
  src/features/posts/components/rating-button-group.tsx
  src/features/posts/hooks/use-update-rating.ts
  src/features/posts/models/post.tsx
  src/lib/utils.ts
Labels: enhancement

#15 Select genres and movies
  package-lock.json
  package.json
  src/components/shared/multi-genre-select.tsx
  src/components/shared/multi-movie-select.tsx
  src/components/shared/navbar.tsx
  src/components/shared/sidebar/app-sidebar.tsx
  src/components/shared/sidebar/sidebar-no-icon-item.tsx
  src/components/ui/badge.tsx
  src/components/ui/popover.tsx
  src/features/boards/components/message-board.tsx
  src/features/boards/hooks/use-get-board.ts
  src/features/boards/models/board.ts
  src/features/genres/hooks/use-favorite-genres.ts
  src/features/genres/hooks/use-favorite-movies.ts
  src/features/genres/hooks/use-get-favorite-genres.ts
  src/features/genres/hooks/use-get-genres.ts
  src/features/genres/hooks/use-get-movies.ts
  src/features/genres/models/genres.ts
  src/features/genres/models/movie.ts
  src/features/posts/components/sidebar-genre-items.tsx
  src/routeTree.gen.ts
  src/routes/(auth)/_auth.message-board.$boardId.tsx
  src/routes/(auth)/_auth.new-post.tsx
  src/routes/(auth)/_auth.select-genres.tsx
  src/routes/(auth)/_auth.tsx
  src/routes/(public)/_public.tsx
Labels: enhancement

#17 update all of comparisons between the board id and genre id to board …
  src/components/shared/sidebar/app-sidebar.tsx
  src/features/posts/components/sidebar-genre-items.tsx
  src/routes/(auth)/_auth.new-post.tsx
  src/routes/(auth)/_auth.select-genres.tsx
Labels: bug

#22 fixed a bug on delete-comment
  src/components/comments/comment-list.tsx
  src/features/comments/hooks/use-delete-comment.ts
Labels: bug, enhancement
